name: macro
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - black
  - numpy
  - scipy
  - matplotlib
  - plotly
  - pyyaml
  - pip

  # Optional: editor/dev tools
  - ipython
  - mypy
  - ruff
  - pytest

  # Pip install from pyproject.toml
  - pip:
      - -e . # Install the package in editable mode